spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234

mybatis:
  mapper-locations: classpath:mapper/*xml

server:
  port: 8080

weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "f3EBxGArPSLcuA/hMpozbP7r5qSMPfyto+DPhoG6O3pCeMhvbje4mmGdHyDBhg3nqSaESnS3Lf44giG5C1qekw=="